### ISSUE TITLE
Инсталляция русского языка на Flarum 

### ISSUE THREAD

**Issue by dimitricheckin** [flarum-lang/russian#15]
Здравствуйте. 
Может кто-нибудь подсказать как инсталировать Русский язык на Flarum? 
Composer я занрузил, Flarum тоже, а дальше не понимаю, что делать. 
Куда вот это вот воткнуть (composer require flarum-lang/russian) 
Спасибо.

**Comment by KitsuneSolar** [comment]
https://github.com/flarum-lang/russian#install--%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

**Comment by KitsuneSolar** [comment]
> Куда вот это вот воткнуть (composer require flarum-lang/russian)
В терминал сервера. Зайти на сервер можно по SSH.
Больше информации предоставил хостер.

**Comment by dimitricheckin** [comment]
> https://github.com/flarum-lang/russian#install--%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

Спасибо конечно. Но я уже тут всё прочитал. 
Не понятно, куда идти и что делать.

**Comment by KitsuneSolar** [comment]
@dimitricheckin выше ответил.

**Comment by dimitricheckin** [comment]
> 

Дело в том что я не программист. 
Я не знаю где и что такое терминал. 
Я думал, что можно найти инструкции по установке Русского языка, но найти я их не смог. 
Всё что я нашел - это инструкции для программистов или людей знающих это дело. 
А для обычного пользователя инструкций нет. И на Ютубе тоже нет. 
Для чего был переведен этот форум не понятно, если пакет обычный пользователь не может установить.

**Comment by dimitricheckin** [comment]
Но за попытку помочь, огромное спасибо.

**Comment by dimitricheckin** [comment]
Если кто-нибудь может мне помочь установить Русский язык на Flarum, буду очень признателен. 

I would greatly appreciate it if anybody could help me install a Russian language pack on my Flarum forum.

**Comment by KitsuneSolar** [comment]
@dimitricheckin ну тут очень просто.
Пока что фларум можно установить только при помощи Композера - это менеджер пакетов для языка программирования ПХП. Обновлять форум тоже надо через Композер.

Фларум сейчас разрабатывает свой пакетный менеджер, но на сколько он совершенен - этого я сказать не могу. Это пока что молодой движок и разработчики делают упор в область создания платформы для расширения, а не общего законченного продукта. Возможно, в будущем что то поменяется.

Тебе всё равно придётся учится использовать Композер хотя бы для установки сторонних расширений форума.

**Comment by KitsuneSolar** [comment]
> Если кто-нибудь может мне помочь установить Русский язык на Flarum, буду очень признателен.
> 
> I would greatly appreciate it if anybody could help me install a Russian language pack on my Flarum forum.

Спроси в ветке форума: https://discuss.flarum.org/d/1545-russian-language-pack/548

Может быть кто-то поможет. Но без хотя бы начальных навыков работы с Композером, делать тут нечего. Имхо.

**Comment by dimitricheckin** [comment]
> @dimitricheckin выше ответил.

Юрий, помогите пожалуйста установить Русский язык на мой Flarum форум. 
Я вам заплачу.

**Comment by KitsuneSolar** [comment]
> > @dimitricheckin выше ответил.
> 
> Юрий, помогите пожалуйста установить Русский язык на мой Flarum форум. Я вам заплачу.

Обратитесь на форум по ссылке выше. Сейчас у меня нет технической возможности оказывать тех-поддержку.

**Comment by dimitricheckin** [comment]
> > > @dimitricheckin выше ответил.
> > 
> > 
> > Юрий, помогите пожалуйста установить Русский язык на мой Flarum форум. Я вам заплачу.
> 
> Обратитесь на форум по ссылке выше. Сейчас у меня нет технической возможности оказывать тех-поддержку.

Помогите. А я вам форум могу помочь перевести. 
Я английский хорошо знаю.

**Comment by dimitricheckin** [comment]
> Это пока что молодой движок

"Это пока что молодой движок" 
Это уже не молодой движок. 
Ребята создали прекрасный продукт. Но у них в команде походу менеджеров вообще нет. 
Или есть, но такие которые вообще не понимают что происходит и что надо делать дальше. 
Походу этот движок так и загнется.

**Comment by KitsuneSolar** [comment]
@dimitricheckin как пожелаете. Я Вам предложит зайти на форум. Если хорошо знаете английский, можете напрямую пообщаться с другими пользователями и разработчиками.

На этом я тему закрываю.

**Comment by dimitricheckin** [comment]
Что значит, как пожелаю? 
Я желаю, чтобы мне помогли )))

**Comment by dimitricheckin** [comment]
И на форуме я тоже уже написал.
